### ISSUE TITLE
Can I use this to play j2me on ios 3?

### ISSUE THREAD

**Issue by Baggette** [SquirrelJME/SquirrelJME#140]
Sorry if I didn't follow the format correctly im not sure how I was supposed to do it.

**Comment by Baggette** [comment]
nvm

**Comment by SergioFLS** [comment]
I think I've seen a port of some third-party JVM on Cydia. Not sure if it supports iOS 3 though

**Comment by Baggette** [comment]
> I think I've seen a port of some third-party JVM on Cydia. Not sure if it supports iOS 3 though

there is a third party jvm on cydia that does support ios 3

**Comment by Baggette** [comment]
I don't know what to do with it though
