### ISSUE TITLE
SquirrelJME Java SE fails to launch if a JAR is invalid or DRM encrypted

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#24]
When I added several games in the lib folder, SquirrelJME (latest auto) now doesn't launch. It was fixed by removing some games again. Including log.
[squirrellog.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3315497/squirrellog.txt)
![image](https://user-images.githubusercontent.com/17219314/59940778-e071cd00-945b-11e9-8d63-f471d9ad4616.png)

**Comment by sczther** [comment]
Seems to be certain games having a problem, it now doesn't work even with a single game:

> DBUG0 csv.VMResourceAccess::open (:149) -- rAS(zip, META-INF/MANIFEST.MF) = true
> ****************************
> *** EXTERNAL STACK TRACE ***
> java.lang.IndexOutOfBoundsException: AE09 0 0
> 	at net.multiphasicapps.io.ByteDeque.get(ByteDeque.java:488)
> 	at net.multiphasicapps.io.DynamicHistoryInputStream.peek(DynamicHistoryInputStream.java:244)
> 	at net.multiphasicapps.zip.streamreader.ZipStreamReader.nextEntry(ZipStreamReader.java:149)
> 	at cc.squirreljme.vm.InMemoryClassLibrary.loadZip(InMemoryClassLibrary.java:117)
> 	at cc.squirreljme.vm.PathSuiteManager.loadLibrary(PathSuiteManager.java:133)
> 	at cc.squirreljme.vm.MergedSuiteManager.loadLibrary(MergedSuiteManager.java:81)
> 	at cc.squirreljme.vm.VMResourceAccess.open(VMResourceAccess.java:138)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.nativeMethod(SpringThreadWorker.java:1590)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.__vmInvokeStatic(SpringThreadWorker.java:4613)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.__singleStep(SpringThreadWorker.java:3415)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.run(SpringThreadWorker.java:1941)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.run(SpringThreadWorker.java:1911)
> 
> *** INTERNAL STACK TRACE ***
> Thread #3: LauncherRefresh
>     at cc/squirreljme/runtime/cldc/io/ResourceInputStream.open:(Ljava/lang/String;Ljava/lang/String;)Lcc/squirreljme/runtime/cldc/io/ResourceInputStream; @ 20 [INVOKESTATIC] (ResourceInputStream.java:192)
>     at javax/microedition/swm/Suite.__manifest:()Lnet/multiphasicapps/tool/manifest/JavaManifest; @ 35 [INVOKESTATIC] (Suite.java:530)
>     at javax/microedition/swm/Suite.__suiteInfo:()Lcc/squirreljme/runtime/swm/SuiteInfo; @ 17 [INVOKEVIRTUAL] (Suite.java:595)
>     at javax/microedition/swm/Suite.<init>:(Ljava/lang/String;)V @ 35 [INVOKEVIRTUAL] (Suite.java:100)
>     at javax/microedition/swm/__SystemSuiteManager__.__getSuite:(Ljava/lang/String;)Ljavax/microedition/swm/Suite; @ 62 [INVOKESPECIAL] (__SystemSuiteManager__.java:183)
>     at javax/microedition/swm/__SystemSuiteManager__.__allSuites:()Ljava/util/List; @ 29 [INVOKESTATIC] (__SystemSuiteManager__.java:146)
>     at javax/microedition/swm/__SystemSuiteManager__.getSuites:(Ljavax/microedition/swm/SuiteType;)Ljava/util/List; @ 22 [INVOKESTATIC] (__SystemSuiteManager__.java:105)
>     at cc/squirreljme/runtime/launcher/ui/MidletMain.refresh:()V @ 100 [INVOKEINTERFACE] (MidletMain.java:144)
>     at cc/squirreljme/runtime/launcher/ui/MidletMain$1.run:()V @ 4 [INVOKEVIRTUAL] (MidletMain.java:262)
>     at java/lang/Thread.__start:()V @ 141 [INVOKEVIRTUAL] (Thread.java:740)
> 
> ****************************
> Exception in thread "Thread-2" java.lang.IndexOutOfBoundsException: AE09 0 0
> 	at net.multiphasicapps.io.ByteDeque.get(ByteDeque.java:488)
> 	at net.multiphasicapps.io.DynamicHistoryInputStream.peek(DynamicHistoryInputStream.java:244)
> 	at net.multiphasicapps.zip.streamreader.ZipStreamReader.nextEntry(ZipStreamReader.java:149)
> 	at cc.squirreljme.vm.InMemoryClassLibrary.loadZip(InMemoryClassLibrary.java:117)
> 	at cc.squirreljme.vm.PathSuiteManager.loadLibrary(PathSuiteManager.java:133)
> 	at cc.squirreljme.vm.MergedSuiteManager.loadLibrary(MergedSuiteManager.java:81)
> 	at cc.squirreljme.vm.VMResourceAccess.open(VMResourceAccess.java:138)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.nativeMethod(SpringThreadWorker.java:1590)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.__vmInvokeStatic(SpringThreadWorker.java:4613)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.__singleStep(SpringThreadWorker.java:3415)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.run(SpringThreadWorker.java:1941)
> 	at cc.squirreljme.vm.springcoat.SpringThreadWorker.run(SpringThreadWorker.java:1911)
> DBUG0 csrca.NativeDisplayAccess$SwingPanel::windowClosing (:752) -- Window is closing!
> TODO1 js.AccessController::checkPermission @ 18h (:36) -- Check permission: ("java.lang.RuntimePermission" "exitVM.0")
> DBUG0 csvs.SpringDisplayEventCallback::__exec (:203) -- VM in exit state, canceling display function.


With AkiraHero1.1.jar MD5: 378462f52ef0c702f5cff01db22312c4

**Comment by XerTheSquirrel** [comment]
Okay the JAR you gave me uses some kind of DRM encryption. The least I can do right now is to make it not crash when such a file exists.

![image](https://user-images.githubusercontent.com/11927855/59945593-13a16580-9436-11e9-8986-a1e1a897cb1f.png)

**Comment by XerTheSquirrel** [comment]
This has been fixed, if the JAR is invalid then it will be ignored.

![image](https://user-images.githubusercontent.com/11927855/59949147-451f2e80-9440-11e9-84bc-62c3128ebf7b.png)
