### ISSUE TITLE
Bomber by Hadron fails to run with TODO code

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#25]
Log included
[squirrellog.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3315535/squirrellog.txt)
Bomber.jar MD5: be2f755d5af0b7bcba6a11a73c163cf1

**Comment by XerTheSquirrel** [comment]
This should be fixed in the latest code.

**Comment by sczther** [comment]
Now gets past the issue

**Comment by XerTheSquirrel** [comment]
Closing, thanks!
