### ISSUE TITLE
Anarchy 2087 gets stuck loading

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#27]
The game launches, but the progress bar halts after a while.
[squirrellog.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3316674/squirrellog.txt)
Anarchy 2087 CZ.jar MD5: 91a57dc3d6f3f1fc87bddd399925816c

**Comment by XerTheSquirrel** [comment]
This may be specific to SpringCoat as it is really slow and PNG decompression is a bit intensive, if you wait long enough it should eventually load the images.

**Comment by XerTheSquirrel** [comment]
Tracking in https://github.com/XerTheSquirrel/SquirrelJME/issues/37 now.
