### ISSUE TITLE
Bomber gets stuck launching

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#28]
[squirrellog.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3316682/squirrellog.txt)
Bomber.jar MD5: be2f755d5af0b7bcba6a11a73c163cf1

**Comment by XerTheSquirrel** [comment]
This may be specific to SpringCoat as it is really slow and PNG decompression is a bit intensive, if you wait long enough it should eventually load the images.

**Comment by sczther** [comment]
Had it running for close to an hour, nothing showed up. Adding the longer log:
[bomber_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3317698/bomber_log.txt)

**Comment by XerTheSquirrel** [comment]
Seems this is a game which just keeps loading PNGs are a long time, either they do it inefficiently or it has many resources. This should get better when SummerCoat comes.

**Comment by XerTheSquirrel** [comment]
Tracking in https://github.com/XerTheSquirrel/SquirrelJME/issues/37 now.
