### ISSUE TITLE
Contra 4 reaches fatal exception

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#30]
[contra4_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3317609/contra4_log.txt)
Contra4.jar MD5: 56d0486f93d12f4e967bd12d69c50d6a

**Comment by XerTheSquirrel** [comment]
It looks like this is referring to a class in the jar file which does not exist so perhaps maybe the jar is corrupt?

**Comment by XerTheSquirrel** [comment]
The inner class parsing issue has been fixed.
