### ISSUE TITLE
Playman Summer Games 2 reaches fatal exception

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#34]
[summergames_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3320993/summergames_log.txt)
Summer Games2.jar MD5: 2cbb00996fc46e52dcf3479afccb01c3

**Comment by XerTheSquirrel** [comment]
Looks like this wants to load class `e` which does not exist.

**Comment by XerTheSquirrel** [comment]
This has been corrected but the game uses M3G so it will not work after this point.
