### ISSUE TITLE
Tomb Raider Legend reaches fatal exception

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#35]
[tombraiderlegend_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3321132/tombraiderlegend_log.txt)
Tomb Raider Legend.jar MD5: d692c3d8a0476bf32d64ebd736a04b2e

**Comment by XerTheSquirrel** [comment]
Looks like this tries to load class `q` which does not exist.

**Comment by XerTheSquirrel** [comment]
Class `q` uses m3g.

**Comment by XerTheSquirrel** [comment]
It's use of m3g is unrelated, the inner classes are not parsed correctly for this class. So the parse error will be fixed but then it will fail due to the lack of m3g.

**Comment by XerTheSquirrel** [comment]
Removed the inner class check in the class file parser, so this should continue.
