### ISSUE TITLE
Tony Hawk's American Wasteland reaches fatal exception

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#36]
[tonyhawksamericanwasteland_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3321167/tonyhawksamericanwasteland_log.txt)
Tony Hawk's American Wasteland.jar MD5: 720bd45d96efa647e0af89ab28be6e76

**Comment by XerTheSquirrel** [comment]
Closing, this uses a Nokia API and will be tracked here https://github.com/XerTheSquirrel/SquirrelJME/issues/11 .
