### ISSUE TITLE
Earth Invasion reaches exception

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#45]
[earthinvasion_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3341979/earthinvasion_log.txt)
Gameloft_Earth_Invasion.jar MD5: ebc93f682fea37ce2bb66608b3aef13d

**Comment by XerTheSquirrel** [comment]
Tracking in #11 as this uses Nokia APIs.
