### ISSUE TITLE
Launcher crashes

### ISSUE THREAD

**Issue by sczther** [SquirrelJME/SquirrelJME#46]
Tried adding some small games and poof!
[crash_log.txt](https://github.com/XerTheSquirrel/SquirrelJME/files/3341989/crash_log.txt)

**Comment by XerTheSquirrel** [comment]
This might be a manifest which has a UTF-8 BOM in it or similar.

**Comment by XerTheSquirrel** [comment]
Closing, this should not occur anymore.
