### ISSUE TITLE
Can't load any game

### ISSUE THREAD

**Issue by Keeganab** [SquirrelJME/SquirrelJME#67]
I try to load game Gothic 3 on my 3ds using SquirrelJME in Retroarch but getting this error: 

![IMG_8436](https://user-images.githubusercontent.com/52284375/77256152-ac3a6f80-6c6c-11ea-83f3-f5f460156a96.jpg)

I download summercoatrom from SquirrelJME site but there are only .mkd files and I don't know where to put this on sd card.

**Comment by XerTheSquirrel** [comment]
Hi! Please see #53 , this is a work in progress and is not complete at this time.
